import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import { copyFile, mkdir } from 'node:fs/promises';
import { dirname, join } from 'node:path';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

// Path to the Obsidian vault where the plugin should be emitted in dev mode.
// The plugin is copied to <vault>/.obsidian/plugins/<plugin-id>/.
const VAULT_PATH = 'C:/Users/daniel.munhoz_sensed/Documents/Obsidian/teste';
const PLUGIN_ID = 'obsidian-sentry';

const prod = process.argv[2] === 'production';

async function copyToVault() {
	const destDir = join(VAULT_PATH, '.obsidian', 'plugins', PLUGIN_ID);
	await mkdir(destDir, { recursive: true });
	for (const file of ['main.js', 'manifest.json', 'styles.css']) {
		try {
			await copyFile(file, join(destDir, file));
			console.log(`Copied ${file} -> ${join(destDir, file)}`);
		} catch (err) {
			if (err.code !== 'ENOENT') {
				throw err;
			}
		}
	}
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
	plugins: [
		{
			name: 'copy-to-vault',
			setup(build) {
				build.onEnd(async () => {
					if (!prod) {
						await copyToVault();
					}
				});
			},
		},
	],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
